# Generated by Django 2.2.2 on 2020-06-24 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('email', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(default=None, max_length=500, verbose_name='Hospital')),
                ('Address', models.CharField(default=None, max_length=500, verbose_name='Address')),
                ('contact_number', models.CharField(default=None, max_length=15, verbose_name='Contact Number')),
                ('h_type', models.CharField(default=None, max_length=5, verbose_name='Hospital Type')),
                ('beds_occupied', models.IntegerField(blank=True, default=0, null=True, verbose_name='Occupied Ventilators')),
                ('beds_vacant', models.IntegerField(blank=True, default=0, null=True, verbose_name='Vacant Ventilators')),
                ('total_beds', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Beds')),
                ('ventilators_occupied', models.IntegerField(blank=True, default=0, null=True, verbose_name='Occupied Ventilators')),
                ('ventilators_vacant', models.IntegerField(blank=True, default=0, null=True, verbose_name='Vacant Ventilators')),
                ('total_ventilators', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Ventilators')),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last Updated')),
                ('password', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
