# Generated by Django 2.2.2 on 2020-06-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esic', '0002_auto_20200624_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='GLink',
            field=models.CharField(default=None, max_length=500, verbose_name='GLink'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='iw_occupied',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Occupied beds'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='iw_vacant',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Vacant beds'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_iw',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Beds'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='beds_occupied',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Occupied beds'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='beds_vacant',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Vacant beds'),
        ),
    ]
